### ISSUE TITLE
require not found

### ISSUE THREAD

**Issue by matthellstrom** [brzpegasus/ember-cli-nwjs#44]
I'm trying to add a menubar to a project and I'm getting an error on require('nw.gui'). Not sure I'm adding it in the right place, I just put it in the body of index.html. Could you let me know what I'm doing wrong? Here's the code, it's from a nwjs tutorial. I'm just getting started with this.

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hello Ember</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    {{content-for 'head'}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/hello-ember.css">

    {{content-for 'head-footer'}}
  </head>
  <body>
    {{content-for 'body'}}

  <script>
    var nw = require('nw.gui');

    // Window menu
    var windowMenu = new nw.Menu({
        type: 'menubar'
    });

    // Help menu
    var helpMenu = new nw.Menu();

    // Add to window menu
    windowMenu.append(new nw.MenuItem({
        label: 'Help',
        submenu: helpMenu
    }));

    // About sub-entry
    helpMenu.append(new nw.MenuItem({
        label: 'about',
        click: function(){
            alert('I made this!');
        }
    }));

    // Assign to window
    nw.Window.get().menu = windowMenu;
  </script>

    <script src="assets/vendor.js"></script>
    <script src="assets/hello-ember.js"></script>

    {{content-for 'body-footer'}}
  </body>
</html>

Here's the error from the ember nw script and the js console:

[45788:1005/224247:ERROR:nw_shell.cc(336)] ReferenceError: require is not defined
    at file:///Development/ember/hello-ember/dist/index.html:38:14

**Comment by matthellstrom** [comment]
Here's the code again, without the script tags, apparently they make it not display properly. This is just the area that doesn't work, specifically the first line.

    var nw = require('nw.gui');

    // Window menu
    var windowMenu = new nw.Menu({
        type: 'menubar'
    });

    // Help menu
    var helpMenu = new nw.Menu();

    // Add to window menu
    windowMenu.append(new nw.MenuItem({
        label: 'Help',
        submenu: helpMenu
    }));

    // About sub-entry
    helpMenu.append(new nw.MenuItem({
        label: 'about',
        click: function(){
            alert('I made this!');
        }
    }));

    // Assign to window
    nw.Window.get().menu = windowMenu;

**Comment by brzpegasus** [comment]
You won't be able to set up the menu bar there. The `require` function is typically available to you globally in NW.js, but Ember CLI's module loader ends up rewriting the `require` function to be something else. The addon injects some code [before](https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-head.js#L11-L12) and [after](https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-footer.js) your Ember app loads, in order to work around this.

You could try to replace `var nw = require('nw.gui');` with `var nw = requireNode('nw.gui')` but if the `nw.gui` code internally needs to require other modules during the menu bar setup, it will likely not work well.

What I do in this [example app](https://github.com/brzpegasus/ember-nw-markdown/blob/master/app/nw/menu.js#L10) is wrap the menu bar code in an `Ember.Object` that only gets [initialized](https://github.com/brzpegasus/ember-nw-markdown/blob/master/app/initializers/nw-menu.js#L7-L11) when the app is ready, and after we've [patched up](https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-footer.js#L15-L20) the `require` function.

I hope this clarifies things a bit. If you haven't yet checked out the talk I gave at Wicked Good Ember 2015 on Ember + NW.js, have a look [here](https://www.youtube.com/watch?v=vqmPVhZ__WI). It might shed some more light into how things work.

**Comment by matthellstrom** [comment]
Ok cool, thanks. I'll try it.

On Friday, October 9, 2015, Estelle DeBlois <notifications@github.com>
wrote:

> You won't be able to set up the menu bar there. The require function is
> typically available to you globally in NW.js, but Ember CLI's module loader
> ends up rewriting the require function to be something else. The addon
> injects some code before
> <https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-head.js#L11-L12>
> and after
> <https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-footer.js>
> your Ember app loads, in order to work around this.
>
> You could try to replace var nw = require('nw.gui'); with var nw =
> requireNode('nw.gui') but if the nw.gui code internally needs to require
> other modules during the menu bar setup, it will likely not work well.
>
> What I do in this example app
> <https://github.com/brzpegasus/ember-nw-markdown/blob/master/app/nw/menu.js#L10>
> is wrap the menu bar code in an Ember.Object that only gets initialized
> <https://github.com/brzpegasus/ember-nw-markdown/blob/master/app/initializers/nw-menu.js#L7-L11>
> when the app is ready, and after we've patched up
> <https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-footer.js#L15-L20>
> the require function.
>
> I hope this clarifies things a bit. If you haven't yet checked out the
> talk I gave at Wicked Good Ember 2015 on Ember + NW.js, have a look here
> <https://www.youtube.com/watch?v=vqmPVhZ__WI>. It might shed some more
> light into how things work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brzpegasus/ember-cli-nwjs/issues/44#issuecomment-146983083>
> .
>


-- 
Matt Hellstrom
Hellstrom Enterprises LLC
(509) 995-8705 cell
(509) 995-1570 office

**Comment by matthellstrom** [comment]
Watched the video Estelle, thanks for that! This is going to be great,
rewriting a cobol enterprise system for a sporting goods wholesaler, I
think it's going to work well! Really excited to learn how to do this.

Matt

On Fri, Oct 9, 2015 at 1:51 PM, Estelle DeBlois <notifications@github.com>
wrote:

> You won't be able to set up the menu bar there. The require function is
> typically available to you globally in NW.js, but Ember CLI's module loader
> ends up rewriting the require function to be something else. The addon
> injects some code before
> <https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-head.js#L11-L12>
> and after
> <https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-footer.js>
> your Ember app loads, in order to work around this.
>
> You could try to replace var nw = require('nw.gui'); with var nw =
> requireNode('nw.gui') but if the nw.gui code internally needs to require
> other modules during the menu bar setup, it will likely not work well.
>
> What I do in this example app
> <https://github.com/brzpegasus/ember-nw-markdown/blob/master/app/nw/menu.js#L10>
> is wrap the menu bar code in an Ember.Object that only gets initialized
> <https://github.com/brzpegasus/ember-nw-markdown/blob/master/app/initializers/nw-menu.js#L7-L11>
> when the app is ready, and after we've patched up
> <https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-footer.js#L15-L20>
> the require function.
>
> I hope this clarifies things a bit. If you haven't yet checked out the
> talk I gave at Wicked Good Ember 2015 on Ember + NW.js, have a look here
> <https://www.youtube.com/watch?v=vqmPVhZ__WI>. It might shed some more
> light into how things work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brzpegasus/ember-cli-nwjs/issues/44#issuecomment-146983083>
> .
>



-- 
Matt Hellstrom
Hellstrom Enterprises LLC
(509) 995-8705 cell
(509) 995-1570 office

**Comment by matthellstrom** [comment]
BTW, I'll probably just have a menubar in the html, then they'd be able to
run it from a browser too if they wanted.

On Sat, Oct 10, 2015 at 4:59 PM, Matt Hellstrom <matt@hellstrominc.com>
wrote:

> Watched the video Estelle, thanks for that! This is going to be great,
> rewriting a cobol enterprise system for a sporting goods wholesaler, I
> think it's going to work well! Really excited to learn how to do this.
>
> Matt
>
> On Fri, Oct 9, 2015 at 1:51 PM, Estelle DeBlois <notifications@github.com>
> wrote:
>
>> You won't be able to set up the menu bar there. The require function is
>> typically available to you globally in NW.js, but Ember CLI's module loader
>> ends up rewriting the require function to be something else. The addon
>> injects some code before
>> <https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-head.js#L11-L12>
>> and after
>> <https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-footer.js>
>> your Ember app loads, in order to work around this.
>>
>> You could try to replace var nw = require('nw.gui'); with var nw =
>> requireNode('nw.gui') but if the nw.gui code internally needs to require
>> other modules during the menu bar setup, it will likely not work well.
>>
>> What I do in this example app
>> <https://github.com/brzpegasus/ember-nw-markdown/blob/master/app/nw/menu.js#L10>
>> is wrap the menu bar code in an Ember.Object that only gets initialized
>> <https://github.com/brzpegasus/ember-nw-markdown/blob/master/app/initializers/nw-menu.js#L7-L11>
>> when the app is ready, and after we've patched up
>> <https://github.com/brzpegasus/ember-cli-nwjs/blob/master/lib/resources/shim-footer.js#L15-L20>
>> the require function.
>>
>> I hope this clarifies things a bit. If you haven't yet checked out the
>> talk I gave at Wicked Good Ember 2015 on Ember + NW.js, have a look here
>> <https://www.youtube.com/watch?v=vqmPVhZ__WI>. It might shed some more
>> light into how things work.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brzpegasus/ember-cli-nwjs/issues/44#issuecomment-146983083>
>> .
>>
>
>
>
> --
> Matt Hellstrom
> Hellstrom Enterprises LLC
> (509) 995-8705 cell
> (509) 995-1570 office
>



-- 
Matt Hellstrom
Hellstrom Enterprises LLC
(509) 995-8705 cell
(509) 995-1570 office
