### ISSUE TITLE
Can't get the toolbar to go away

### ISSUE THREAD

**Issue by pjcarly** [brzpegasus/ember-cli-nwjs#46]
First of all, superb addon, thanks for the work.

Excuses for opening an issue, I read through the documentation and tried several options, but none of them seem to work.

I managed to get my Ember app built, but for some reason I can't get rid of the toolbar when running the .exe that nwjs built.

I created a nw-package.js file in the config folder, I tried a few variations of the file below, and according to the documentation I think this should be the file.

```js
module.exports = {
  "name": "My App Name",
  'version': '0.12.2',
  "window": {
    "toolbar": false,
    "frame": false
  }
};
```

However, when running `ember nw:package` the exe created always has the toolbar.
Am I doing something wrong?

Thanks for taking a look,
Regards,
pjcarly

**Comment by johnhuffsmith** [comment]
This goes in `package.json`, NOT in `nw-package.js`

    "window": {
    "toolbar": false,
    "frame": false
      }

**Comment by pjcarly** [comment]
Cheers that was it!
