### ISSUE TITLE
nw.js refuses to start

### ISSUE THREAD

**Issue by shripathee** [brzpegasus/ember-cli-nwjs#48]
Getting these errors:
```
Error: Could not find module `fs` imported from `(require)`
Uncaught Error: Could not find module `ember-resolver` imported from `happyfox-web/app`
```

Ember CLI version: 2.2.0-beta.3
Ember version: 2.3.0-beta.3

**Comment by brzpegasus** [comment]
I'll take a look later tonight. Tied up with client work at the moment!

**Comment by shripathee** [comment]
Okay :)

**Comment by brzpegasus** [comment]
Everything is working with Ember CLI 1.13.13 and Ember 2.3.0-beta.3. So it's definitely an issue with the beta version of the CLI. Maybe something with the loader. I'll keep you posted.

**Comment by brzpegasus** [comment]
Ok, so the problem is because the new `loader.js` defines a variable called [`global`](https://github.com/ember-cli/loader.js/blob/v3.6.0/loader.js#L2), which overrides NW's own `global`. Joy!

```js
// loader.js
var global = this;

(function() {
  // ...

  loader = {
    noConflict: function(aliases) {
      var oldName, newName;

      for (oldName in aliases) {
        if (aliases.hasOwnProperty(oldName)) {
          if (oldGlobals.hasOwnProperty(oldName)) {
            newName = aliases[oldName];

            global[newName] = global[oldName];
            global[oldName] = oldGlobals[oldName];
          }
        }
      }
    }
  };
```

I'm guessing we can rename `global` to `_this` or something that doesn't conflict in `loader.js`, but I'm not 100% sure. That's just from quickly looking over the file.

**Comment by rwjblue** [comment]
Great job tracking this down! 

loader.js@3.6.1 is released with your fix...

**Comment by brzpegasus** [comment]
w00t!

**Comment by shripathee** [comment]
Updated loader.js to 3.6.1. nw is working now. Thanks guys :)
