### ISSUE TITLE
Facility to create a separate environment for native app

### ISSUE THREAD

**Issue by shripathee** [brzpegasus/ember-cli-nwjs#55]
Right now, we have certain settings exclusively for native app. For e.g: locationType: 'hash'.
Is it possible to have a separate environment for native app, which modifies the configuration already present for 'development' or 'production'?

**Comment by brzpegasus** [comment]
You can either do something like this:

```js
var ENV = {
  locationType: process.env.EMBER_CLI_NW ? 'hash' : 'auto',
  // ...
};
```

or this:

```js
var ENV = {
  // common config
};

if (process.env.EMBER_CLI_NW) {
  // override settings for NW.js
}
```

or introduce a new environment altogether in your `config/environment.js`:

```js
var ENV = {
  // common config
};

if (environment === 'nwjs') {
  // override settings for NW.js  
}
```

But if you do the latter, you'll have to run all the `ember nw[:*]` commands with `--environment=nwjs`.

**Comment by shripathee** [comment]
Thanks. It would be nice if the above can be added to the README since this is a fairly common use case.
