### ISSUE TITLE
App won't run, white screen

### ISSUE THREAD

**Issue by matthellstrom** [brzpegasus/ember-cli-nwjs#56]
When I just run ember nw I'm getting an error and the app won't come up. Here's the error I get:

![image](https://cloud.githubusercontent.com/assets/14794936/12821528/a28cfa74-cb18-11e5-920a-3371c5dc5a20.png)

Is there something wrong with ember, or with my code? It runs fine in the browser.

**Comment by brzpegasus** [comment]
If the app comes up blank, can you still open the dev tools within NW.js and see if you can expand the error stack and get more details? Is this a brand new project? In other words, are you able to reproduce on a barebone Ember CLI-generated app?

**Comment by matthellstrom** [comment]
I'm not sure how to open the dev tools. I can't get to the console.

It's not a new app, and it was working about a week ago. Something happened in the last couple of days, maybe an add-on I installed?

**Comment by brzpegasus** [comment]
> I'm not sure how to open the dev tools. I can't get to the console.

You can enable the toolbar (`window.toolbar` setting in `package.json`), then click on the gear icon in the upper right cornder.

> It's not a new app, and it was working about a week ago. Something happened in the last couple of days, maybe an add-on I installed?

Hard to debug "remotely". If being able to access the console doesn't provide you with more info, you could try to revert to earlier commits just to narrow down on when the error started happening and which piece of code might be the culprit.

**Comment by matthellstrom** [comment]
That totally worked! I found the problem right away, forgot I could enable that toolbar.

Thank you so much!

**Comment by brzpegasus** [comment]
Good to hear!
